# hwpanel: hardware layout written by skins/panels.py (edit panel_specs.py, not this file)

[tab BRAIDS]
popup cx=143 cy=218 w=190 h=61 label="ENGINE" key=engine field=none accent=9cf23a cols=4 cw=190
knob cx=189 cy=336 r=31 label="COARSE" key=octave_transpose ns=0 bw=109 ink_dim=1a1a1a img=hw_mi_w.svg
knob cx=300 cy=336 r=31 label="FM" key=fm ns=0 bw=109 ink_dim=1a1a1a img=hw_mi_w.svg
knob cx=76 cy=447 r=31 label="TIMBRE" key=timbre ns=0 bw=130 ink_dim=1a1a1a img=hw_mi_t.svg
knob cx=300 cy=447 r=31 label="COLOR" key=color ns=0 bw=130 ink_dim=1a1a1a img=hw_mi_r.svg
knob cx=443 cy=250 r=30 label="ATTACK" key=attack ns=0 bw=113 ink_dim=1a1a1a img=hw_mi_w.svg
knob cx=559 cy=250 r=30 label="DECAY" key=decay ns=0 bw=113 ink_dim=1a1a1a img=hw_mi_w.svg
knob cx=443 cy=390 r=30 label="SUSTAIN" key=sustain ns=0 bw=113 ink_dim=1a1a1a img=hw_mi_w.svg
knob cx=559 cy=390 r=30 label="RELEASE" key=release ns=0 bw=113 ink_dim=1a1a1a img=hw_mi_w.svg
knob cx=501 cy=540 r=34 label="LEVEL" key=volume ns=0 bw=130 ink_dim=1a1a1a img=hw_mi_r.svg
knob cx=800 cy=270 r=52 label="FREQUENCY" key=cutoff ns=0 bw=130 ink_dim=1a1a1a img=hw_mi_wb.svg
knob cx=726 cy=460 r=30 label="RESONANCE" key=resonance ns=0 bw=130 ink_dim=1a1a1a img=hw_mi_w.svg
knob cx=874 cy=460 r=30 label="ENV AMOUNT" key=filt_env ns=0 bw=130 ink_dim=1a1a1a img=hw_mi_t.svg
knob cx=1041 cy=250 r=30 label="ATTACK" key=f_attack ns=0 bw=113 ink_dim=1a1a1a img=hw_mi_t.svg
knob cx=1157 cy=250 r=30 label="DECAY" key=f_decay ns=0 bw=113 ink_dim=1a1a1a img=hw_mi_t.svg
knob cx=1041 cy=390 r=30 label="SUSTAIN" key=f_sustain ns=0 bw=113 ink_dim=1a1a1a img=hw_mi_t.svg
knob cx=1157 cy=390 r=30 label="RELEASE" key=f_release ns=0 bw=113 ink_dim=1a1a1a img=hw_mi_t.svg
qlinks "BRAIDS A" = engine,octave_transpose,fm,timbre,color,cutoff,resonance,filt_env,attack,decay,sustain,release,f_attack,f_decay,f_sustain,f_release
qlinks "BRAIDS B" = volume
