# hwpanel: hardware layout written by skins/panels.py (edit panel_specs.py, not this file)

[tab CHORUS]
enum_h cx=360 cy=426 label="" key=mode sw=158 sh=220 img=hw_juno_led.svg img_on=hw_juno_ledon.svg
slider_v cx=840 cy=423 w=34 h=230 label="MIX" key=mix ns=0 bw=150 img=hw_juno_cap.svg base=hw_juno_tr.svg
slider_v cx=1000 cy=423 w=34 h=230 label="BRIGHTNESS" key=brightness ns=0 bw=150 img=hw_juno_cap.svg base=hw_juno_tr.svg
qlinks "CHORUS" = mode,mix,brightness
