# hwpanel: hardware layout written by skins/panels.py (edit panel_specs.py, not this file)

[tab PSX VERB]
frame x=10 y=142 w=325 h=566 title="MODE"
enum_v cx=172 cy=453 label="MODE" key=model sw=135 sh=64
frame x=341 y=142 w=651 h=566
knob cx=666 cy=400 r=52 label="DECAY" key=decay bw=130
frame x=998 y=142 w=271 h=566
knob cx=1133 cy=216 r=40 label="MIX" key=mix bw=130
knob cx=1133 cy=400 r=40 label="INPUT" key=input_gain bw=130
knob cx=1133 cy=584 r=40 label="LEVEL" key=reverb_level bw=130
qlinks "PSX VERB A" = model,decay,mix,-,-,-,-,-,input_gain
qlinks "PSX VERB B" = reverb_level
