#!/usr/bin/env python3
"""Consolidate every module's build result into ~/force-staging/manifest.{json,md}.

Reads the built zips under modules/<name>/vst/dist and the per-module logs under
~/force-staging/logs/ to record status and, for failures, the first error line.
"""
import json
import os
import re
import shutil

WORK = os.path.expanduser("~/force-work")
MODDIR = os.path.join(WORK, "modules")
STAGING = os.path.expanduser("~/force-staging")
LOGS = os.path.join(STAGING, "logs")

MODULES = [
    ("schwung-hush1", "charlesvestal/schwung-hush1", "Synth"),
    ("schwung-303", "charlesvestal/schwung-303", "Synth"),
    ("schwung-hank", "charlesvestal/schwung-hank", "Synth"),
    ("schwung-braids", "charlesvestal/schwung-braids", "Synth"),
    ("schwung-chiptune", "charlesvestal/schwung-chiptune", "Synth"),
    ("move-anything-plaits", "j3threejay/move-anything-plaits", "Synth"),
    ("move-everything-mrhyde", "handcraftedcc/move-everything-mrhyde", "Synth"),
    ("denis-move", "filliformes/denis-move", "Synth"),
    ("schwung-6W6", "athousanddetails/schwung-6W6", "Drums"),
    ("schwung-8W8", "athousanddetails/schwung-8W8", "Drums"),
    ("schwung-9W9", "athousanddetails/schwung-9W9", "Drums"),
    ("schwung-cw-78", "athousanddetails/schwung-cw-78", "Drums"),
    ("schwung-libpo32", "mestela/schwung-libpo32", "Drums"),
    ("schwung-sophie", "mestela/schwung-sophie", "Drums"),
    ("weird-dreams-move", "filliformes/weird-dreams-move", "Drums"),
    ("schwung-space-delay", "charlesvestal/schwung-space-delay", "FX"),
    ("schwung-psxverb", "charlesvestal/schwung-psxverb", "FX"),
    ("schwung-midiverb", "charlesvestal/schwung-midiverb", "FX"),
    ("schwung-junologue-chorus", "charlesvestal/schwung-junologue-chorus", "FX"),
    ("schwung-tapescam", "charlesvestal/schwung-tapescam", "FX"),
    ("schwung-filter", "charlesvestal/schwung-filter", "FX"),
    ("schwung-ducker", "charlesvestal/schwung-ducker", "FX"),
    ("schwung-4keq", "athousanddetails/schwung-4keq", "FX"),
    ("schwung-busdriver", "legsmechanical/schwung-busdriver", "FX"),
]

ERR = re.compile(r'(fatal error:.*|error: .*|undefined reference to.*|no chain_params|popup \'.*|skin folder must be named.*|IndexError:.*)')


def first_error(name):
    override = {
        "schwung-sophie": "no static parameter list: chain_params is built at runtime "
                          "(sophie.c write_chain_params()); the skin generator needs >=1 parameter",
    }
    if name in override:
        return override[name]
    p = os.path.join(LOGS, name + ".log")
    if not os.path.isfile(p):
        return None
    for line in open(p, encoding="utf-8", errors="replace"):
        m = ERR.search(line)
        if m:
            return m.group(1).strip()[:200]
    return "build or release failed (see log)"


def main():
    os.makedirs(STAGING, exist_ok=True)
    rows = []
    for name, repo, kind in MODULES:
        d = os.path.join(MODDIR, name)
        row = {"name": name, "repo": repo, "category": kind, "commit": None,
               "version": None, "build": "failed", "zip": None, "reason": None}
        try:
            row["commit"] = os.popen("git -C %s rev-parse HEAD" % d).read().strip() or None
        except Exception:
            pass
        mj = os.path.join(d, "src", "module.json")
        if os.path.isfile(mj):
            try:
                row["version"] = str(json.load(open(mj)).get("version"))
            except Exception:
                pass
        dist = os.path.join(d, "vst", "dist")
        zips = [f for f in (os.listdir(dist) if os.path.isdir(dist) else [])
                if f.endswith("-mpc-armv7.zip")]
        if zips:
            src = os.path.join(dist, zips[0])
            dst = os.path.join(STAGING, zips[0])
            shutil.copy2(src, dst)
            row["build"] = "ok"
            row["zip"] = zips[0]
        else:
            row["reason"] = first_error(name)
        rows.append(row)
    json.dump(rows, open(os.path.join(STAGING, "manifest.json"), "w"), indent=1)

    ok = [r for r in rows if r["build"] == "ok"]
    with open(os.path.join(STAGING, "manifest.md"), "w") as f:
        f.write("# Force staging manifest\n\n")
        f.write("Generated by build_all.py + consolidate.py. Zips in this folder are MPC OS VST2\n")
        f.write("installers for armv7 (Cortex-A17/Force, glibc <= 2.32). Built for staging only -- "
                "nothing was installed on any device.\n\n")
        f.write("| Module | Repo | Commit | Version | Category | Build | Zip |\n")
        f.write("|---|---|---|---|---|---|---|\n")
        for r in rows:
            f.write("| %s | %s | %s | %s | %s | %s | %s |\n" % (
                r["name"], r["repo"], (r["commit"] or "")[:10], r["version"] or "",
                r["category"], "OK" if r["build"] == "ok" else "FAILED", r["zip"] or "-"))
        f.write("\n## Builds that failed (skipped)\n\n")
        for r in rows:
            if r["build"] != "ok":
                f.write("- **%s** (%s): %s\n" % (r["name"], r["repo"], r["reason"]))
        f.write("\n**%d/%d built OK.**\n" % (len(ok), len(rows)))
    print("staged %d/%d" % (len(ok), len(rows)))
    for r in rows:
        if r["build"] != "ok":
            print("  FAILED %-24s %s" % (r["name"], r["reason"]))


if __name__ == "__main__":
    main()